site_name: LSP mode

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  logo: examples/logo-mini.png
  favicon: examples/logo-mini.png
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/emacs-lsp/lsp-mode
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yonchovski

repo_name: emacs-lsp/lsp-mode
repo_url: https://github.com/emacs-lsp/lsp-mode

markdown_extensions:
  - pymdownx.superfences
  - codehilite
  - toc:
      permalink: '#'

plugins:
  - search
  - awesome-pages
  - git-revision-date-localized
