name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: purcell/setup-emacs@master
        with:
          version: 27.1

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      # `lsp-register-custom-settings` should not be used for defining client
      # settings, see its description for details
      - name: Do not overwrite user settings
        run: "! git grep lsp-register-custom-settings -- clients"

      - name: Resolve dependency
        run: eask install-deps --dev

      - name: Run Indentation Lint
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }} \
          | grep \.el | grep -v \.dir-locals\.el \
          | xargs -t -I^ eask emacs -q --batch ^ --eval "\
              (let ((require-final-newline t)) \
                (require 'flycheck) \
                (eval-buffer) \
                (untabify (point-min) (point-max)) \
                (indent-region (point-min) (point-max)) \
                (save-buffer))" \
          ; git diff --exit-code
