name: CI

on: [push, pull_request]

jobs:
    unix-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                emacs-version:
                    - 26.1
                    - 26.2
                    - 26.3
                    - 27.1
                    - snapshot

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: "3.6"
                  architecture: "x64"

            - uses: purcell/setup-emacs@master
              with:
                  version: ${{ matrix.emacs-version }}

            - uses: conao3/setup-cask@master
              with:
                  version: 0.8.4

            - name: Setup cmake
              uses: jwlawson/actions-setup-cmake@v1.4
              with:
                 cmake-version: '3.0.x'

            - name: Check cmake
              run: "cmake --version"

            - name: Install LLVM and Clang
              uses: KyleMayes/install-llvm-action@v1
              with:
                 version: "10.0"
                 directory: ${{ runner.temp }}/llvm

            - name: Check clangd
              run: "which clangd"

            - name: Install depedencies
              run: "pip3 install python-language-server"

            - name: Run tests
              run:
                make unix-ci

    windows-test:
        runs-on: windows-latest
        strategy:
            matrix:
                emacs-version:
                    - 27.1

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-python@v2
              with:
                  python-version: "3.6"
                  architecture: "x64"

            - uses: jcs090218/setup-emacs-windows@v3
              with:
                version: ${{ matrix.emacs-version }}

            - name: Install depedencies
              run: "pip install python-language-server"

            - name: Run tests
              run:
                make windows-ci
